import Header from "@/components/common/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`relative `}
      >
        <div className="fixed w-full items-center justify-between left-1/2 transform -translate-x-1/2 z-50">
          <Header />
        </div>
         <main className="mt-0">
          {children}
        </main>
      </body>
    </html>
  );
}
