import Header from "@/components/common/Header";
import "./globals.css";
import { Nunito_Sans } from 'next/font/google';

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'], // add only weights you need
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={nunitoSans.className}>
      <body
        className={`relative `}
      >
        <div className="fixed w-full items-center justify-between left-1/2 transform -translate-x-1/2 z-50">
          <Header />
        </div>
         <main className="mt-0">
          {children}
        </main>
      </body>
    </html>
  );
}
